n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'
lmd: 0.1
lmd_sem: 0.1
tau: 1
contrast: 'us_x'  # choose from {un, su, us, us_x}
sim: 'dot'  # choose from {dot, cos}

SSL_AUG: 'DuoRec'